config/routes.rb
Dojitsu::Application.routes.draw do   
  get "dashboard/index"
  get "dashboard/whatsNew"
  get "dashboard/message"
  get "dashboard/myChallenge"
  get "dashboard/dashboardIndex"
  get "dashboard/against_others"
  get "dashboard/against_myself"
  # user registration & 3rd party logins
  match 'users/auth/:provider/callback', :to=>'authentications#create'

  devise_for :users, :controllers => { :registrations => "registrations"}
  resources :authentications

  resources :challenges do
    collection do
    	post "storeWinner"
      get "show_soc"
      get "task_update"
      get "show_per"
      get "my_challenge"
      get "invitee_accepted_req"
      get "challenge_comp"
      get "task_update_c"
      get "date_updateEnd"
      get "date_updateStart"
      get "message"
      get "add_task_link"
      get "add_task_fun"
      get "update_status"
      get "socialPeople"
      get "nonLoginShowPersonal"
      get "nonLoginShowSocial"
      get "nonLoginIndex"
      get "paginationTest"
      get "update_status_af_meg"
      put "update_task_soc"
      get "scoreboard_main"
      get "filter"
      get "trophies"
      get "scoreboard"
      get "publish"
      get "title_update"
      get "task_update"
      get "desc_update"
      get "title_soc_update"
      get "desc_soc_update"
	  get "update_tasks_list"
	  put "update_tasks_list"
	  get "myscore_update_self_report"
      put :update_attribute_on_the_spot 
      get :get_attribute_on_the_spot
	  get "score_soc_update"
      get "search_people"
	  get "change_challenge_status"
	  get "update_status_again"
	  get "mForWinner"
	  get "registerToMessage"
	  get "deleteWinner"	
	  get "winnerListPopup"
	  get "whoAccepted"
	  get "whoThinking"
	  get "whoDeclined"	
	  get "myAccepted"
	  get "myDeclined"
	  get "myThinking"
    end
  end

  # static pages
  match '/aboutus', :to=>'static#aboutus'
  match '/contactus', :to=>'static#contactus'
  resources :user_connections do
    collection do
      get "sendInvitation"
      get "myDojo"
      get "people"
      get "invite_contact"
      get "delete_contact"
    end
  end

  resources :messages do
    collection do
      post "storemessage"
      get "message"
      get "newmessage"
      get "individualAllMessage"
      get "markUnread"      		
    end	
  end 


  # root page
  root :to=>'static#home'
end

app/models/user_connection.rb
class UserConnection < ActiveRecord::Base
  belongs_to :user
  has_one :usermail
end

app/controllers/user_connections_controller.rb
class UserConnectionsController < ApplicationController
  before_filter :authenticate_user!


  def index
    @user_connections = Challenge.all;
	#raise current_user.facebook.uid.inspect
    #@user_connections = FbGraph::User.me(AAAAAAITEghMBAGwEqIvywCnasJzScTAZAIKgx1mzI0SE8wWbEe78FmLF2DsrZBwnZBqQZB5hubkGq8ZAT9zYEJDeEMsYlQiZBSujBZBip28ZCNrxtAQ7JJPp)
    #friendslist = @user_connections.friends
  end
  
  
  def new
    @user_connection = UserConnection.new
     render :action => "new"
  end

  
  def create
    @user_connection = UserConnection.new(params[:user_connection])
   
      if @user_connection.save
       redirect_to(@user_connection, :notice => 'user was successfully created.')
      else
    render :action => "invite_contact"    
      end
	  end

  def profile
    prsofile ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token).fetch
  end

  def sendInvitation	
	if !params[:inviteIds].nil?
		params[:inviteIds].each do |inviteId|
			current_user.user_connections.find_or_create_by_target_id(:target_id => inviteId )
		end
	end
  end
  
  def dashbord
  end
  
 def delete_contact
  @useconnection = params[:id]
	render :layout => false
		
	end 
	  
 def invite_contact
      	render :layout => false
	end 
	
	def connections_selection
  end
  
  def myDojo
	render :layout => false
  end
  
  def people
	render :layout => false
  end
  
  
  def destroy
    @useconnection = UserConnection.where(:target_id => params[:id]).first
    @useconnection.destroy
	redirect_to :action => 'index'
  end
  
  
  

end

app/helpers/user_connections_helper.rb
module UserConnectionsHelper
end

app/views/user_connections/_currentUserTrophy.erb
<% noOfFirstRank = 0 %>
<% noOfSecondRank = 0 %>
<% noOfThirdRank = 0 %>
<% noOfFourthRank = 0 %>
<% noOffifthRank = 0 %>
<% noOfSixRank = 0 %>

<% current_user.challenges.each do |eachChallenge| %>
<% if eachChallenge.social_type.trophy != nil %>
	<% if eachChallenge.social_type.trophy.rank == 1 %>                          
     <% noOfFirstRank += 1 %>                                                    
   <% elsif eachChallenge.social_type.trophy.rank == 2 %>                          
      <% noOfSecondRank += 1 %>                                                                      
   <% elsif eachChallenge.social_type.trophy.rank == 3 %>                                        
       <% noOfThirdRank += 1 %>                                                         
   <% elsif eachChallenge.social_type.trophy.rank == 4 %>                          
       <% noOfFourthRank += 1 %>                                                                      
   <% elsif eachChallenge.social_type.trophy.rank == 5 %>                          
       <% noOffifthRank += 1 %>                                                                      
   <% elsif eachChallenge.social_type.trophy.rank == 6 %>                          
       <% noOfSixRank += 1 %>                                                   
   <% end %>
<% end %>   
<% end %>                       
<% if noOfFirstRank > 0 %>                          
<%= image_tag("trophy_gold.png") %><font id="trophyAlign"><%= noOfFirstRank %></font>
<% end %>                                                                    
<% if noOfSecondRank > 0 %>                          
<%= image_tag("trophy_green.png") %><font id="trophyAlign"><%= noOfSecondRank %></font>
<% end %>                                                                         
<% if noOfThirdRank > 0 %>                                        
 <%= image_tag("trophy_orange.png") %><font id="trophyAlign"><%= noOfThirdRank %></font>
<% end %>                                                             
<% if noOfFourthRank > 0 %>                          
 <%= image_tag("trophy_blue.png") %><font id="trophyAlign"><%= noOfFourthRank %></font>
<% end %>                                                                          
<% if noOffifthRank > 0 %>                          
 <%= image_tag("trophy_purple.png") %><font id="trophyAlign"><%= noOffifthRank %></font>
<% end %>                                                                          
<% if noOfSixRank > 0 %>                          
 <%= image_tag("trophy_platinum.png") %><font id="trophyAlign"><%= noOfSixRank %></font>
<% end %> 

app/views/user_connections/_dojofriends.html.erb
<% allConnections = UserConnection.find(:all, :conditions =>["user_id=?", current_user.id]) %>
                    				
					<% allConnections.each  do |eachConnection| %>
						<tr id="row_<%= eachConnection.target_id %>" onload="alert("hi");" onclick="function_<%= eachConnection.target_id %>();">
						<td>
						<%=image_tag(FbGraph::User.new(eachConnection.target_id).fetch.picture, :id=>"image_#{eachConnection.target_id}") %>
						<span class="fbusername"><%= FbGraph::User.new(eachConnection.target_id).fetch.name %></span>
						<span > 
						</td>
						<td>
					
						<%= image_tag('btn_msg_up.png', :id => "image1_#{eachConnection.target_id}", :class =>"private_msg" )%>
			
						
						<%= link_to image_tag("btn_delete_up.png" , :id => "image2_#{eachConnection.target_id}"), delete_contact_user_connections_path( :id=>eachConnection.target_id), :class=>"remove" %></span> 
						</td>
						</tr>
						<tr > 
							<td colspan="2"> 
								<hr/>
							</td>
						</tr> 
			
                                       
						<style>
						#row_<%= eachConnection.target_id %>:hover
						  {
							background-color: #f4f4f4;
						  }
						  #image
						  {
						  padding-right:-20px;
						  }
						</style>
					<script>
						$(document).ready(function(){
												$("#image1_<%= eachConnection.target_id%>").hide();
												$("#image2_<%= eachConnection.target_id%>").hide();
											   
												  $("#row_<%= eachConnection.target_id %>").mouseover(function(){
														$("#image1_<%= eachConnection.target_id%>").show()
														$("#image2_<%= eachConnection.target_id%>").show()
												  });
										
												$(document).mouseout(function(){
																$("#image1_<%= eachConnection.target_id%>").hide();
																$("#image2_<%= eachConnection.target_id%>").hide();
												 });
								 });
				</script>
						
					<% end %>
                                       

app/views/user_connections/_invitations.html.erb
<%= stylesheet_link_tag('jquery.facebook.multifriend.select.css','challenges.css','jquery-ui')%>

<%= form_for :challenge, :url => {:controller=> "challenges",:action => "create"},:html=>{:multipart => true, :name => "challenge_form", :onclick=> "return validate_form_fields(this);"} do |f| -%>
<p>            
 <%= image_tag("invitee.PNG", :id => "inviteBtn",   :class=>"invitees" )%>
  
 <%= text_field_tag :invitees, nil , :id => "invitees_id", :class=> "hidden" %>

 
</p>                             
<% end %>

app/views/user_connections/_invitations_private.html.erb
<%= stylesheet_link_tag('jquery.facebook.multifriend.select.css','challenges.css')%>

<%= form_for :challenge, :url => {:controller=> "challenges",:action => "create"},:html=>{:multipart => true, :name => "challenge_form", :onclick=> "return validate_form_fields(this);"} do |f| -%>
<p>            
 <%= image_tag("invite.PNG", :id => "inviteBtn",   :class=>"invitees" )%>
  
 <%= text_field_tag :invitees, nil , :id => "invitees_id", :class=> "hidden" %>

 <div id="jfmfs-container-wrapper" style="display: none">
  <div id="jfmfs-container">
  </div>
 </div>
</p>                             
<% end %>

<script type="text/javascript" charset="utf-8">        
(function($j) { 
 var selectorObz = {    
  filter_default: "Search By Name",
  friend_fields: "id,name,last_name&access_token="+'<%= current_user.facebook.access_token%>'
 }

 $j('.invitees').live('click', function(){
  $j( "#jfmfs-container-wrapper" ).dialog({
   modal: true,
   resizable: false,
   closeText: "",
   position: 'center',
   title: 'Invite Participants',
   width: '725px',
   open: function(event, ui) { $j("#jfmfs-container").jfmfs(selectorObz); },
   buttons: {                                             
                Cancel: function() {
     $j("#jfmfs-container").data('jfmfs').clearSelected(); 
     $j('#inviteBtn').val("INVITE PARTICIPANTS");    
     $j(this).dialog( "close" );
    },
    Save: function() {
     var friendSelector = $j("#jfmfs-container").data('jfmfs');
     var selectedFriends = friendSelector.getSelectedIds();
     $j('#invitees_id').val(selectedFriends);
        $j('#inviteBtn').val("INVITE PARTICIPANTS (" + selectedFriends.length + ")");   
    $j(this).dialog( "close" );
		jQuery.support.cors = true;
		$.get('/user_connections/sendInvitation', 
			{inviteIds:selectedFriends},
			function(data) {

			}, 'script'
		);
     } 
   }
   
  });
 })          

 })(jQuery);                              
 </script>

app/views/user_connections/delete_contact.html.erb
<%= stylesheet_link_tag('simple-tabs','colorbox','jquery.cluetip.css','jquery-ui','ui.progressbar','ui.theme', 'main')%>
<%= javascript_include_tag('simple-tabs','ui.progressbar.js','soc-per','on_the_spot','jquery.colorbox-min','jquery.tools.min','messages','fbWallPost')%>

<div id="ch_main_div"> 
<b><h4> Remove <%=FbGraph::User.new(@useconnection).fetch.name %> from mydojo </h4></b>
	<div id="ch_main_div1"> 
	<%=image_tag(FbGraph::User.new(@useconnection).fetch.picture) %> &nbsp; Are you sure you want to remove  <b><%=FbGraph::User.new(@useconnection).fetch.name %></b> from your dojo 
	<hr/>
	<table width=100%>
	<tr>
	<td>
	<%= button_to "DONE",   user_connection_path(:id => @useconnection), :method => :delete, :class => "selectable-del" %>
	</td>
	<td>
	<%= link_to "CANCEL", user_connections_path, :class => "selectable"%>
	</td>
	</tr>
	</table>
</div>
</div>

app/views/user_connections/index.html.erb
<%= stylesheet_link_tag('challenges.css','simple-tabs','jquery-ui', 'ui.core','ui.progressbar', 'main','colorbox','userconnections')%>
<%= javascript_include_tag('jquery.facebook.multifriend.select','simple-tabs','ui.progressbar','jquery.colorbox-min','on_the_spot','ajaxPageLoad','user_connection','messages')%>
<%= render 'layouts/loggedinbody'%>

<% as= current_user.challenges.size %>
<section bgcolor="#f4f4f4" class="topbar" id="topbbarid" >	
<section class="invitee_button" >
		<%= render :partial => 'invitations' %>
			<section  class="username">
				<%=current_user.facebook.name%>
			</section>			
		</section>		
</section>

<section id="ch_main_section5">
<p class="user"><%=current_user.facebook.name%></p>
	<table border="1px">
		<tr width="600px">
			<td width="100px" height="200px" align="left">      
				<% picturePath = current_user.facebook.picture('large')%>
				<% if picturePath.nil?   
					 picturePath = current_user.facebook.picture
				end%>
				<%= image_tag picturePath %>   
			</td>
			<td width="570px" height="200px">
				<table>
					<tr>
						<td width="100px">
							<span class="titlecol" >MEMBER SINCE</span></td>
						</td>
						<td align="left">
							<span class="subtitlecol" >
							<% date = 0 %>
							<% month =0%>
							<% date = current_user.created_at.to_date%>
								<b><%month= "#{date.strftime(" %B" )}".scan(/..../) %> <%= month[0] %><%= date.strftime(" %d, %Y" )  %></b>
							</span>
						</td>
					</tr> 
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>   
					<tr>
						<td width="100px">
							<span class="titlecol" >ACHIEVEMENTS</span>
						</td>
						<td align="left" >
							                                                                        
                     <%= render :partial=> "currentUserTrophy" %>
                        	
						</td>
					</tr>
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>   
					<tr>
						<td width="100px" height="10px">
							<span class="titlecol" >CURRENT CITY</span></td>
						</td>
						<td align="left" >
							<span class="subtitlecol" >
								<b><%= current_user.facebook.location.name rescue 'N/A' %></b>
							</span>
						</td>
					</tr>
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>   
					<tr>
						<td width="100px">
							<span class="titlecol" >HOME TOWN</span>
						</td>
						<td align="left" height="10px">
							<span class="subtitlecol" >
								<b><%= current_user.facebook.hometown.name rescue 'N/A' %></b>
							</span>
						</td>
					</tr>
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>   
					<tr>
						<td width="100px">
							<span class="titlecol" >SEX</span></td>
						</td>
						<td align="left" height="10px">
							<span class="subtitlecol" >
								<b><%= (current_user.facebook.gender).capitalize rescue 'N/A' %></b>
							</span>
							</td>
					</tr>
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>
					<tr>
						<td width="100px">
							<span class="titlecol" >BIRTH DAY</span></td>
						</td>
						<td align="left" height="10px">
							<span class="subtitlecol" >
							<% birthday = 0 %>
							<% birth_month= 0%>
							<%birthday = current_user.facebook.birthday rescue 'N/A' %>
								<b><%birth_month= "#{birthday.strftime(" %B" )}".scan(/..../) %> <%= birth_month[0] %><%= birthday.strftime(" %d, %Y" )  %></b>
							</span>
						</td>
					</tr>
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>
					<tr id="about_me">
						<td width="100px">
							<span class="titlecol" >ABOUT ME</span></td>
						</td>
						<td align="left" height="10px">
							
							<% if current_user.facebook.bio.nil?%>
							
							<% else %>
							<span class="subtitlecol"  id="about_me1">
								<b><%= truncate "#{current_user.facebook.bio rescue 'N/A'}", :length=>15 %>&nbsp;</b><a href="#" onclick="fun();">more</a></span><%= image_tag("icon_edit.png" , :id=>"edit_info") %></span>
						    <% end %>
						</td>						
					</tr> 
					<tr> 
						<td colspan="2"> 
							<hr/>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	 </table>
	
	<table width="100%" border="0" class="marginst">
		<tr>
			<td colspan="3">
    			<ul class="tabs">
    				<li><a href="#tab1"><b>MY DOJO</b></a></li>
    				<li><a href="#tab2"><b>CHALLENGES</b></a></li>
				</ul>
			</td>
		</tr>
		<tr>
			<td>
				<section class="tab_container1">
					<section id="tab1" class="tab_content2">
						<section id="myDojo"></section>
						<section id="myDojo1"></section>
					</section>
						<script>
							$.dojitsuAjaxPage.renderAjaxPageLoad("/user_connections/myDojo","#myDojo","#myDojo1");
						</script>
					<section id="tab2" class="tab_content2"><br>
						<section id="people"></section>
                            <section id="people1"></section>
                     </section>
					<script>
                         $.dojitsuAjaxPage.renderAjaxPageLoad("/user_connections/people","#people","#people1");
					</script>
			</td>
		</tr>
	</table>
	
<section id="jfmfs-container-wrapper" margin-top:0px;="display: none">
  <section id="jfmfs-container">
  </section>
 </section>
 <style>
 .user 
{
	font-size :20px;
	text-transform: uppercase;
	color: #F8981D;
}

 </style>
 
<script>
	function fun()
		{
			document.getElementById("about_me1").innerHTML="<b><%=current_user.facebook.bio rescue 'N/A' %></b>";
		}
</script>

<script>
$(document).ready(function(){
		$("#edit_info").hide();
		$("#about_me").mouseover(function(){
				$("#edit_info").show()
		  });
		$(document).mouseout(function(){
						$("#edit_info").hide();
		 });
});
</script>


<script type="text/javascript" charset="utf-8">        
(function($j) { 
 var selectorObz = {    
  filter_default: "Search By Name",
  friend_fields: "id,name,last_name&access_token="+'<%= current_user.facebook.access_token%>'
 }

 $j('.invitees').live('click', function(){
  $j( "#jfmfs-container-wrapper" ).dialog({
   modal: true,
   resizable: false,
   closeText: "",
   position: 'center',
   title: 'Invite Participants',
   width: '725px',
   open: function(event, ui) { $j("#jfmfs-container").jfmfs(selectorObz); },
  buttons: {                                             
 	Invite: function() {
     var friendSelector = $j("#jfmfs-container").data('jfmfs');
     var selectedFriends = friendSelector.getSelectedIds();
     $j('#invitees_id').val(selectedFriends);
        $j('#inviteBtn').val("INVITE PARTICIPANTS (" + selectedFriends.length + ")");   
    $j(this).dialog( "close" );
		jQuery.support.cors = true;
		$.get('/user_connections/sendInvitation', 
			{inviteIds:selectedFriends},
			function(data) {
			}, 'script'
		);
     } ,
	  Cancel: function() {
     $j("#jfmfs-container").data('jfmfs').clearSelected(); 
     $j('#inviteBtn').val("INVITE PARTICIPANTS");    
     $j(this).dialog( "close" );
    }
   }
  });
 }
 )          
})(jQuery);

$('.ui-button').live('click', function(){
  $.dojitsuAjaxPage.renderAjaxPageLoad("/user_connections/myDojo","#myDojo","#myDojo1");
    $(".tables").replaceWith($('.tables'));
  });
 </script>

app/views/user_connections/invite.html.erb
<%= stylesheet_link_tag('jquery.facebook.multifriend.select.css','challenges.css','jquery-ui')%>

<%= form_for :challenge, :url => {:controller=> "challenges",:action => "create"},:html=>{:multipart => true, :name => "challenge_form", :onclick=> "return validate_form_fields(this);"} do |f| -%>
			<p>            
			 <%= image_tag("invitee.PNG", :id => "inviteBtn",   :class=>"invitees" )%>
			  
			 <%= text_field_tag :invitees, nil , :id => "invitees_id", :class=> "hidden" %>


			</p>                             
<% end %>

app/views/user_connections/invite_contact.html.erb
</script>
 <div>

<script>
<div class="platform_dialog_header">Invite Friend</div>

window.fbAsyncInit();
      FB.ui({
          method: 'send',
   
          name: 'Register with Dojitsu',
          link: 'http://www.nytimes.com/2011/06/15/arts/people-argue-just-to-win-scholars-assert.html',
          });
     </script>

</div>

app/views/user_connections/myDojo.html.erb
<% allConnections = UserConnection.find(:all, :conditions =>["user_id=?", current_user.id]) %>
	<% group =Array.new %>
	<% allConnections.each  do |eachConnection| %>
		<% group.push(eachConnection.target_id) %>
	<% end %>
		<script>
			function contactToInvitee() 
				{
				 var contact = '<%= group.join(",") %>';
					window.fbAsyncInit();
					FB.ui({
					  method: 'send',
					  to:contact,
					  name: 'Do your best',
					  link: 'http://www.dojitsu.com'
							 });										 
				 }
		</script>

			<div class="tables">

				<table>
					<td width="10%">
							<label for="search">
							<strong>

							<font color="#8c8c8c"><b style="float: right; font-size :15px;">Total:&nbsp;<%= group.length %><span style="position: relative; top: 5px;">&nbsp;<%= image_tag("btn_msg_up.png", :onclick=>"contactToInvitee()") %></span></b></font>
															
							</strong>

							</label>
					</td>
					<td style="width:80%; padding-left: 56%;"><input type="text" id="search"/>
					<span class="searchbox"><%= image_tag ("searchbutton.PNG") ,:id=>"search_button"%><span>
						
						
					</td>
					<td>
					<p class="invite"><%= render :partial => 'invitations' %>
		<%#= image_tag("invitee.PNG", :width=> "100px" , :height => "30px", :style => "top:10px;" )%>

		<%= hidden_field_tag "myvar", 0%>	
		</p>
					</td>
				</table>
				


				<table width="100%" id="tblData" class="sortable" border=1>
				<thead>
				<tr>

				<th width="85%"><b style="position:relative; color:#666666; padding-left:20px; " >NAME</b></th>
				<th width="15%"><b style=" color:#666666;  " >STATUS </b></th>
				</tr>
				</thead>
				<tbody bgcolor="#ffffff">
				<%= render :partial =>"user_connections/dojofriends" %>
				</tbody>
				</table>
				</div>
				
				<script>
					$('.remove').colorbox();
				</script>
				

				
				

				
				<script type="text/javascript">
							$(document).ready(function()
							{
								$('#search_button').click(function()
								{
									searchTable($('#search').val());
								});
							});
							$(document).ready(function()
							{
								$('#search').keyup(function()
								{
									searchTable($(this).val());
								});
							});
							function searchTable(inputVal)
							{
								var table = $('#tblData');
								table.find('tr').each(function(index, row)
								{
									var allCells = $(row).find('td');
									if(allCells.length > 0)
									{
										var found = false;
										allCells.each(function(index, td)
										{
											var regExp = new RegExp(inputVal, 'i');
											if(regExp.test($(td).text()))
											{
												found = true;
												return false;
											}
										});
										if(found == true)$(row).show();else $(row).hide();
									}
								});
							}
						</script>

<script>
    $(document).ready(function() {
        $(".private_msg").click(function(event) {                                                                                                              
            var targetId = event.target.id;
            //alert("Maisa="+targetId);
            var toAdd = targetId.split("_");
            //alert("1="+toAdd[0]);
            //alert("2="+toAdd[1]);    
            $.dojitsu.renderSendBox("Testing", toAdd[1],"http://www.dojitsu.com", <%= "'"+ challenges_url() +"'"%>);	
        });
    });
 </script>


<div id="tooltip" class="tooltip">
	
</div>





<script>
	function changeVal(str,score) {
		var tot_score = str*score;
		$("#tatal_s").val(tot_score);
	} 
	// execute your scripts when the DOM is ready. this is a good habit
	$(function() {	
		
		$('.task_update_popup').colorbox();
		$('.add_task_popup').colorbox();
		
		$("#date").dateinput({
			format: 'dddd dd, mmmm yyyy',	// the format displayed for the user
			selectors: true,             	// whether month/year dropdowns are shown
			min: -100,                    // min selectable day (100 days backwards)
			max: 100,                    	// max selectable day (100 days onwards)
			offset: [10, 20],            	// tweak the position of the calendar
			speed: 'fast',               	// calendar reveal speed
			firstDay: 1                  	// which day starts a week. 0 = sunday, 1 = monday etc..
		});
	});
	
	// setup tooltip for a single DIV element
	$("#task_list a").tooltip({
		// each trashcan image works as a trigger
		tip: '#tooltip',

		// custom positioning
		position: 'center right',

		// move tooltip a little bit to the right
		offset: [0, 15],

		// there is no delay when the mouse is moved away from the trigger
		delay: 0
	});
	
</script>
<style>
  .ui-datepicker{
    width:20%;
  }

</style>
       <style>
								.remove
								{
								position:relative;
								relative; top:-5px
								}
									.searchbox
						{
						position:relative;
						relative; top:5px
						}
						</style>

app/views/user_connections/new.hrml.erb
<h1><font color="white">New User</font></h1>

<%= render 'invite_contact' %>

<font color="yellow">

app/views/user_connections/people.html.erb
<%= stylesheet_link_tag('userconnections')%>
<div class="dashboardsidebar">
<table bgcolor="#f4f4f4">
	<thead>
		<tr>
			<td width=10%>
			      <font size="4" color="#8c8c8c"><b  id="total">Total: </b><b id="total"><%= current_user.challenges.size %> </b></font>
			</td>
			<td width=40%>
				
						
			</td>
			<td width=50% id="button_new">
			     <%= button_to "", new_challenge_url, :class => "new_challenge_button1", :method => :get%>
			</td>
		</tr>
	</thead>
</table>
	
<div style="overflow-y: auto; overflow-x: width: 10%; hidden;  height : 440px;" id="challengedetails1">
       <%#= render 'dashboard/challengeProgress' %>
</div>
	  
	  
<style>
#select
{
background-color:#ffffff;
width:180px;
border-color:#d7d7d7;
boder:1px solid;
}

#button_new
{
text-align:right;
}
#content2
{
padding-left:260px;
}
#p
{
text-align:right;
}
#content1 {
    background-position: 15% center;
}
</style>

app/views/user_connections/view.js.erb
$( "#preview" ).html( "<%= escape_javascript( render( :partial => "view", :locals => { :view => @user_connection} ) ) %>" );