config/routes.rb
Dojitsu::Application.routes.draw do   
  get "dashboard/index"
  get "dashboard/whatsNew"
  get "dashboard/message"
  get "dashboard/myChallenge"
  get "dashboard/dashboardIndex"
  get "dashboard/against_others"
  get "dashboard/against_myself"
  # user registration & 3rd party logins
  match 'users/auth/:provider/callback', :to=>'authentications#create'

  devise_for :users, :controllers => { :registrations => "registrations"}
  resources :authentications

  resources :challenges do
    collection do
    	post "storeWinner"
      get "show_soc"
      get "task_update"
      get "show_per"
      get "my_challenge"
      get "invitee_accepted_req"
      get "challenge_comp"
      get "task_update_c"
      get "date_updateEnd"
      get "date_updateStart"
      get "message"
      get "add_task_link"
      get "add_task_fun"
      get "update_status"
      get "socialPeople"
      get "nonLoginShowPersonal"
      get "nonLoginShowSocial"
      get "nonLoginIndex"
      get "paginationTest"
      get "update_status_af_meg"
      put "update_task_soc"
      get "scoreboard_main"
      get "filter"
      get "trophies"
      get "scoreboard"
      get "publish"
      get "title_update"
      get "task_update"
      get "desc_update"
      get "title_soc_update"
      get "desc_soc_update"
	  get "update_tasks_list"
	  put "update_tasks_list"
	  get "myscore_update_self_report"
      put :update_attribute_on_the_spot 
      get :get_attribute_on_the_spot
	  get "score_soc_update"
      get "search_people"
	  get "change_challenge_status"
	  get "update_status_again"
	  get "mForWinner"
	  get "registerToMessage"
	  get "deleteWinner"	
	  get "winnerListPopup"
	  get "whoAccepted"
	  get "whoThinking"
	  get "whoDeclined"	
	  get "myAccepted"
	  get "myDeclined"
	  get "myThinking"
    end
  end

  # static pages
  match '/aboutus', :to=>'static#aboutus'
  match '/contactus', :to=>'static#contactus'
  resources :user_connections do
    collection do
      get "sendInvitation"
      get "myDojo"
      get "people"
      get "invite_contact"
      get "delete_contact"
    end
  end

  resources :messages do
    collection do
      post "storemessage"
      get "message"
      get "newmessage"
      get "individualAllMessage"
      get "markUnread"      		
    end	
  end 


  # root page
  root :to=>'static#home'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

	def myChallenge
		render :layout => false
	end
	
	def whatsNew
		render :layout => false
	end
	
	def message
		render :layout => false
	end
	
	def dashboardIndex
		render :layout => false
	end
	
	def against_others
		render :layout => false
	end
	def against_myself
		render :layout => false
	end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_against_myself.erb
<%= stylesheet_link_tag('_against_myself')%>
<script>
 $(document).ready(function() 
    { 
        
        $("#myTable").tablesorter({
        // define a custom text extraction function
        textExtraction: function(node) {
            // extract data from markup and return it 
          if (node.innerHTML.indexOf("%") != -1)
          {
            return node.innerHTML.replace("%","");
          }
            return node.innerHTML;
        }
      
    }); 
        
    } 
); 
	
</script>
<script type="text/javascript" src="http://autobahn.tablesorter.com/jquery.tablesorter.js"></script>

<table width="100%" id="myTable">	
  <thead >
    <tr >
      <th width="40%" class="namespace"><span class="namedetails" >NAME</span></th>
      <th width="5%"></th>
      <th width="35%" id="spancefortext2"><span id="completed_header">COMPLETED</span></th>
      <th width="18%" id="spancefortext3"><span id="spancefortext1">TO GO</span></th>
      <th width="9%" id="spancefortext4">LAST UPDATED</th>
    </tr>

  </thead>
  <tbody>
    <% total_challenges =[]	%>
    <% current_user.challenges.each do |userChallenge| %>
      <% total_challenges<<userChallenge %>	
    <%end%>
    <% taskCompleted=1 %>
    <% total_challenges.take(3).each do |limitChallenge|%>
      <tr id="check" width="50" >
        <td class="bordercolort" >	
          <br>
          <span class="userchallengestyle"><%= limitChallenge.title %></span>
          <br>  
          <% if limitChallenge.instance_of?ChildChallenge %>
            <% @parentChallenge = Challenge.where(:_id => limitChallenge.challenge_id).first%>
            <script>
              var ordId = <%=  orgId = @parentChallenge.user_id %>
            </script>
            <div class="chname"><span id="by_properties" >by </span>
              <% if isStandalone %>
                <%= @parentChallenge.first_name %>
              <% else %>
                <%= FbGraph::User.new(@parentChallenge.user_id).fetch.name %>
              <% end %>                                  
            </div>                     
          <% else %>
            <div class="chname"><span id="by_properties" >by </span>
              <% if isStandalone %>
                <%= current_user.gmauth.first_name %>
              <% else %>
                <%= current_user.facebook.name %>
              <% end %>                                  
            </div>   
          <% end %>
          <span class="stedpoint"><%=  limitChallenge.start_point.value %> - <%= limitChallenge.end_point.value %></span>
        </td>
        <td class="bordercolort">
          <section id="percentagecompleted<%= taskCompleted %>">		</section>
        </td>
        <td class="bordercolort">
          <div class="taskprogress" id="taskprogress<%= taskCompleted %>"></div><br/>
          <% flag1=0 %>
          <% flag2=0 %>
          <% aScore= 0 %>
          <% bScore= 0 %>
          <% limitChallenge.tasks.each do |aTask| %>
            <% if (aTask.is_complete == 1 ) %>
              <% aScore+=Integer(aTask.score) %>
              <% flag1+=1 %>
            <% else %>
              <% bScore += aTask.score.to_i %>
              <% flag2+=1 %>
            <% end %>
          <% end %>
          <div class="completedtask"> 
            <span id="score_points"><%= aScore %> points</span> <br> <span id="score_tasks">(<%= flag1 %>&nbsp;tasks)</span>
          </div>

          <script type="text/javascript">
            $(function() {
              $("#taskprogress<%= taskCompleted %>").progressbar({ value: Math.round(((<%= aScore %>/<%= (aScore+bScore) %>)*100)) });
                $("<p>").attr("id", "checkit").text($("#taskprogress<%= taskCompleted %>").progressbar("option", "value") + "%  ").appendTo("#percentagecompleted<%= taskCompleted %>");
              });
          </script>
        </td>
        <td class="bordercolort" >
          <span class="pointscolor1"> <span id="score_points"><%= bScore %> points </span><br> <span id="score_tasks">(<%= flag2 %>&nbsp;tasks)</span></span>

        </td>
        <td class="bordercolort" >
          <span class = "timestyle1"><%= time_ago_in_words  limitChallenge.created_at%></span><br>
          <%=link_to( image_tag("update.png"), show_per_challenges_path(:id => limitChallenge._id), :class=>"updatebutton") %>
        </td>
        <% taskCompleted+=1 %>	
      </tr>
      
    <%end%>
  </tbody>
</table>

app/views/dashboard/_challengeProgress.html.erb
<%= javascript_include_tag('jquery.tablesorter.min')%>
<%= stylesheet_link_tag('style')%>
   
		<% t=1 %>
			<table   id="myTable" class="tablesorter">
			<thead>
			  <tr><th style="CURSOR: pointer; cursor: hand;" id="content1">NAME</th><th style="CURSOR: pointer; cursor: hand;" id="content2"><p id="p">MY DOJITSU SCORE</p></th></tr>
			</thead>
			<tbody>
				<% current_user.challenges.each do |userChallenge| %>
				<tr valign="top" class="challengerow" onclick="location.href='<%= show_per_challenges_path(:id => userChallenge)  %>'" >
					<td >
						<font family="Arial" color="#666666" size=3"><b><%= userChallenge.title %></b></font><br><font size=2>by </font>
						<% if userChallenge.instance_of?ChildChallenge %>
						   <% @parentChallenge = Challenge.where(:_id => userChallenge.challenge_id).first%>
						   <script>
							var ordId = <%=  orgId = @parentChallenge.user_id %>
						   </script>
						   <b><%= FbGraph::User.new(@parentChallenge.user_id).fetch.name %></b>
						<% else %>
							<b><%= current_user.facebook.name %></b>
						<% end %>
						
						</font><br><%=  userChallenge.start_point.value %> - <%= userChallenge.end_point.value %><br>
						<%if ( userChallenge.child_challenges.size <2 ) %> 
							<%= userChallenge.child_challenges.size >0 ? userChallenge.child_challenges.size : 1  %> contestant<br>
						<% else %>
							<%= userChallenge.child_challenges.size %> contestants<br>
						<% end %>
					</td>
					<td >					
						<div class="taskprogress" id="taskprogress<%= t %>">
						</div>
						<br/>
						<div id="check1">
							<% x=0 %>
							<% y=0 %>
							<% a= 0 %>
							<% b= 0 %>
							<% userChallenge.tasks.each do |aTask| %>
					        <%=  raise aTask.id.inspect  %>
								<% if (aTask.is_complete == 1 ) %>
									<% a+=Integer(aTask.score) %>
									<% x+=1 %>
								<% else %>
									<% b += aTask.score.to_i %>
									<% y+=1 %>
								<% end %>
							<% end %>
							
						<div class="update">
							<%= image_tag("FDFDG.gif", :alt => "Update" , :id=>'update'  ) %>												
						</div>
						<div class="completedtask"> 
							<%= a %> points (<%= x %> &nbsp; tasks)
						</div>
						<div class="notcompleted">
							<font size=3 color="#F8981D"><b>to go:</b></font>&nbsp; <font color="#ffffff"><%= b %> points (<%= y %>&nbsp; tasks)</font>
						</div>
							<script type="text/javascript">
								$(function() {
									$("#taskprogress<%= t %>").progressbar({ value: Math.round(((<%= a %>/<%= (a+b) %>)*100)) });
									$("<p>").attr("id", "check").text($("#taskprogress<%= t %>").progressbar("option", "value") + "% Completed:  ").appendTo("#taskprogress<%= t %>");
								});
							</script>
						</div>
						<div id="points">
							&nbsp;&nbsp;<font size=4><b><%= a %></b></font>
						</div>
					</td>
					<% t+=1 %>																
				</tr>
				<% end %>
			</tbody>

			</table>

app/views/dashboard/_dashboardsidebar.html.erb
<% as= current_user.challenges.size %>

<div class="dashboardsidebar">
	<div class="mychallenge">
		<div id="titlechallenge">
			<div class="my_challenges_box">
				MY CHALLENGES <span class="my_challenges_spancolor"><b>( <%= as %> ) </b></span>
			</div>
			<div class="second_titlechallenge">
				<%= button_to "", new_challenge_url, :class => "new_challenge_button", :method => :get%>
			</div>
		</div>						
		<div class="dashboard_sidebardetails" id="challengedetails">
		<%= render 'dashboard/challengeProgress'%>
		</div>
	</div>
</div>

app/views/dashboard/_messages.html.erb
 <% current_user.inbox.each do |userMessage| %>
        <tr>
            <td width="10%" class="bordercolort" id="name">
			<script>
			 window.fbAsyncInit();
			<% @challenge.child_challenges.each do |aTask| %>
				var len = <%= @challenge.child_challenges.length %>
				var img = <%= aTask.user_id %>
						  FB.api({
                                method: 'fql.query',
                                query: 'SELECT name,pic_square FROM user WHERE uid=' +  <%= aTask.user_id %>
                            }, function(response){
									htmlcontent="<table><tr><td><img src=" + response[0].pic_square + " />"+ response[0].name+"</td><td><%= time_ago_in_words userMessage.created_at %><%= FbGraph::User.new(userMessage.from).fetch.name %><br/><%=h truncate(userMessage.body, :length => 55) %>..</td></tr></table>" ;
                                   $("#name").append(htmlcontent);
                            });
					<% end %>
					</script>
       
            </td>
          </td>
        </tr>
        <% end %>

app/views/dashboard/index.html.erb
<%= javascript_include_tag('ajaxPageLoad','fbWallPost','jquery.colorbox-min', 'simple-tabs-dashboard', 'dashboard_againstmyself')%>
<%= stylesheet_link_tag('jquery-ui', 'ui.theme', 'main', 'dashboard','colorbox','messageCss','simple-tabs-dashboard','dashboard_new')%>
<%= render 'layouts/loggedinbody'%>
<% if session[:isNewChallenge] == "isNew" %>
    <script>
      $.dojitsuWallPost.renderFbWallPost();
    </script>
<% end %>
<span class="mydashbotitle">MY DASHBOARD</span>

<table>
<td>
	<content>
	<table>
	<td>
	<tr>
       <td>
         <div class="dashboardsidebar">
            <div class="mychallenge">
             <div class="menubar">
					<span id="howiamgoindspace"><span id="shadow">HOW AM I DOING?</span></span>
						<div id="selecttb"> 
						<select id ="first" class="first_selct_class" >	
							<option  id ="first" value="others" >AGAINST OTHERS</option>
							<option  id ="first" value="myself" selected="yes">AGAINST MYSELF</option>
						</select>
						
					</div>
					<span id="no_of_tasks"> (3) </span> 
					<%# image_tag , challenges_url, :class => "ds_view_all_challenge", :method => :get%>
					<%=link_to( image_tag("viewallbutton.PNG"), challenges_url, :class=>"ds_view_all_challenge") %>
					<%=link_to( image_tag("newbutton.PNG"), new_challenge_url, :class => "new_challenge") %>

			</div>

				<div id="againstother">
					 <%= render :partial => "dashboard/against_others" %>
				</div>
				<div id="againstmyself">
					 <%= render :partial => "dashboard/against_myself" %>
				</div>
			
            </div>
          </div>
      </td>
        </tr>
       <tr>
          <td>	
              <div class="dashboardsidebar1">
                  <div class="mychallenge2">
                      <div id="titlechallenge">
                          <div id="title" class="title_messages_header">
                             <div class="shadow">new messages <span class="newmessagescount">( <%= current_user.inbox.count %> )</span></div>
                          </div>
                          <div class="second_titlechallenge">
                          	<%=link_to( image_tag("newbutton.PNG"), "#", :class => "new_message_button", :method => :get )%>
                          </div>
                      </div>
                      <div class="messages_box_details" id="challengedetails">
                      <div id="message"></div>
                      <div id="message1" align="center"></div>
                      <script>
                        $.dojitsuAjaxPage.renderAjaxPageLoad("/dashboard/message","#message","#message1");
                      </script>
                  </div>	
              </div>
          </td>
      </tr> 
   </td>
</table>
</content>
</td>
<td valign=top>
    <div class="dashboardsidebar2">
      <div class="whatsnew">
          <div class="shadow1" id="shadowcolor">what's new</div>
          <%=link_to( image_tag("viewallbutton.PNG"), challenges_url, :class=>"ds_view_all", :method => :get) %>
          </div>
          <% if Challenge.whatsNew.count == 0 %>
    <p align="center">No challenges found</p>
<% else %>
<% Challenge.whatsNew.each do |aChallenge| %>
    <div id="contentbox" >
	 
        <%= image_tag("new_banner.png", :class => "imagestyle") %>
        <table width="100%" class="maintable">
            <tr>
              <td width="70%" class="firsttdst">
                  <span class ="chatitle"><%= aChallenge.title%></span>	<br>										
                  by
                  <% if aChallenge.instance_of?ChildChallenge %>
                     <% @parentChallenge = Challenge.where(:_id => aChallenge.challenge_id).first%>
                     <script>
                         var ordId = <%=  orgId = @parentChallenge.user_id %>
                     </script>
                     <b>
                        <% if isStandalone %>
                            <%= @parentChallenge.first_name %>
                        <% else %>
                            <%= FbGraph::User.new(@parentChallenge.user_id).fetch.name %>
                        <% end %>                                  
                     </b>
                  <% else %>
                          <b>
                              <% if isStandalone %>
                                  <%= current_user.gmauth.first_name %>
                              <% else %>
                                  <%= FbGraph::User.new(aChallenge.user_id).fetch.name %>
                              <% end %>                                  
                          </b>
                  <% end %>
<br>	
                  <% if aChallenge.start_point.instance_of?PointDateType %>
                          <%= aChallenge.start_point.value.strftime("%b %d, %Y")%> - <%= aChallenge.end_point.value.strftime("%b %d, %Y")%>
                  <% else %>
                          <%= aChallenge.start_point.value rescue 0%> - <%= aChallenge.end_point.value rescue 0%>
                  <% end %>

                  <% if aChallenge.child_challenges.size<2 %>
                   <%= aChallenge.child_challenges.size%>&nbsp;&nbsp;contestant
                   <%else%>
                  <%= aChallenge.child_challenges.size%>&nbsp;&nbsp;contestants
                  <%end%>
                  <p class="texttransormn">
                          <%=h truncate(aChallenge.description, :length => 15) %>&nbsp;&nbsp;<b><%= link_to "view" , show_soc_challenges_path(:id => aChallenge.id), :class => 'underline_view'   %>	</b>								
              </td>
              <td id="time_td" class="tdalign" >              		
              		<% challengeCreatedAt = aChallenge.created_at.to_i %>              		              		
              		<% freranceTime = Time.now.to_i %>
              		<% diffTime = freranceTime - challengeCreatedAt %>
              		<% if diffTime > 8640 %>
              			<p class = "timestyle"><%= aChallenge.created_at.strftime("%b %d, %Y") %></p>	
              		<% else %>
                  	<p class = "timestyle"><%= time_ago_in_words  aChallenge.created_at%></p>
                  <% end %>	
              </td>
            </tr>
        </table>
    </div>
    <% end %>
<% end %>
      </div>    </td> 

</table>
        
<section class="messages_disply">
<section id="sendNewMessage">
    <%= form_tag newmessage_messages_path, :method => :get do  %>
    <table class="new_messages_table">
      <tr class="bgcolor_messages_tr">
        <td colspan="2">
          <span id="messageTextHead">New Message</span>
        </td>
      </tr>
      <tr class="bgcolor_messages_tr">
        <td width="17%" class="bordercolort1">
          <span id="messageText">T0</span>        
        </td>
        <td width="83%" class="bordercolort1">
          <%= text_field_tag 'to', nil, :size=>"61" %>        </td>
      </tr>
      <tr class="bgcolor_messages_tr">
        <td>
          <span id="messageText">MESSAGE</span>
        </td>
        <td>
          <%= text_area_tag 'message','', :class =>"textareaMessage" %>
        </td>
      </tr>
      <tr class="bgcolor_messages_tr">
        <td class="bordercolort1">
          &nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag("icon_attach_mo.png") %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= image_tag("icon_photo_mo.png") %>
        </td>
        <td class="bordercolort1">
          <section style="float: right;">
            <%= check_box_tag 'toMobile','', false %>
            <%= image_tag("icon_sms_mo.png") %>
          </section>
        </td>
      </tr>
      <tr class="bgcolor_messages_tr">
        <td colspan="2">
          <%= link_to "CANCEL",  dashboard_index_path,:class => "links_cancel_message"%>        
          <%= submit_tag "SEND", :class => "linksNewMessage" %>
        </td>
      </tr>
    </table>
    <% end %>
</section>
</section>    
         

app/views/dashboard/myChallenge.html.erb
<%= javascript_include_tag('jquery.tablesorter.min')%>
<%= stylesheet_link_tag('main','style')%>

<div id="challengedetails">
    <% taskCompleted=1 %>
   
    <table id="myTable" class="tablesorter">
      <% if current_user.challenges.count == 0 %>
          <p align="center">No challenges for you</p>
      <% else %>
      <thead>
          <tr>
              <th id="content1">NAME</th>
              <th id="content2"><span class="position">MY DOJITSU SCORE</span></th>
          </tr>
      </thead>
      <tbody>
          <% current_user.challenges.each do |userChallenge| %>
            <tr valign="top" class="challengerow" onclick="location.href='<%= show_per_challenges_path(:id => userChallenge)  %>'" >
              <td class="bordercolort">	
                 <br> <span class="userchallengestyle"><b><%= userChallenge.title %></b></span><br> <span class="fontsize"> by </span> 
                  <% if userChallenge.instance_of?ChildChallenge %>
                     <% @parentChallenge = Challenge.where(:_id => userChallenge.challenge_id).first%>
                     <script>
                         var ordId = <%=  orgId = @parentChallenge.user_id %>
                     </script>
                     <b>
                        <% if isStandalone %>
                            <%= @parentChallenge.first_name %>
                        <% else %>
                            <%= FbGraph::User.new(@parentChallenge.user_id).fetch.name %>
                        <% end %>                                  
                    </b>                     
                  <% else %>
                      <b>
                          <% if isStandalone %>
                              <%= current_user.gmauth.first_name %>
                          <% else %>
                              <%= current_user.facebook.name %>
                          <% end %>                                  
                      </b>
                  <% end %>
                  <br><%=  userChallenge.start_point.value %> - <%= userChallenge.end_point.value %><br>
                  <%if ( userChallenge.child_challenges.size <2 ) %> 
                     <%= userChallenge.child_challenges.size >0 ? userChallenge.child_challenges.size : 1  %> contestant<br>
                  <% else %>
                     <%= userChallenge.child_challenges.size %> contestants<br>
                  <% end %>
              </td>
              <td class="bordercolort1">					
                  <br><div class="taskprogress" id="taskprogress<%= taskCompleted %>"></div><br/>
                      <div id="check1">
                          <% flag1=0 %>
                          <% flag2=0 %>
                          <% aScore= 0 %>
                          <% bScore= 0 %>
                          <% userChallenge.tasks.each do |aTask| %>
                              <% if (aTask.is_complete == 1 ) %>
                                <% aScore+=Integer(aTask.score) %>
                                <% flag1+=1 %>
                              <% else %>
                                <% bScore += aTask.score.to_i %>
                                <% flag2+=1 %>
                              <% end %>
                          <% end %>
                      <div class="update">
                         <%= image_tag("FDFDG.gif", :alt => "Update")%>												
                      </div>
                      <div class="completedtask"> 
                         <%= aScore %> points (<%= flag1 %>&nbsp;tasks)
                      </div>
                      <div class="notcompleted">
                         <span class="togostyle"><b>to go:</b></span>&nbsp; <span class="pointscolor"><%= bScore %> points (<%= flag2 %>&nbsp;tasks)</span>
                      </div>
                      <script type="text/javascript">
                          $(function() {
                              $("#taskprogress<%= taskCompleted %>").progressbar({ value: Math.round(((<%= aScore %>/<%= (aScore+bScore) %>)*100)) });
                              $("<p>").attr("id", "check").text($("#taskprogress<%= taskCompleted %>").progressbar("option", "value") + "% Completed:  ").appendTo("#taskprogress<%= taskCompleted %>");
                          });
                      </script>
                  </div>
                  <div id="points">
                     &nbsp;&nbsp;<span class="ascoresize"><b><%= aScore %></b></span>
                  </div>													
              </td>																					
              <% taskCompleted+=1 %>															
          </tr>
          <% end %>              
      </tbody>
      <% end %>
    </table>
</div>

app/views/dashboard/whatsNew.html.erb
<% if Challenge.whatsNew.count == 0 %>
    <p align="center">No challenges found</p>
<% else %>
<% Challenge.whatsNew.each do |aChallenge| %>
    <div id="contentbox" >
        <%= image_tag("new_banner.png", :class => "imagestyle") %>
        <table width="100%" class="maintable">
            <tr>
              <td width="70%" class="firsttdst">
                  <span class ="chatitle"><%= aChallenge.title%></span>	<br>										
                  by
                  <% if aChallenge.instance_of?ChildChallenge %>
                     <% @parentChallenge = Challenge.where(:_id => aChallenge.challenge_id).first%>
                     <script>
                         var ordId = <%=  orgId = @parentChallenge.user_id %>
                     </script>
                     <span id="user_name">
                        <% if isStandalone %>
                            <%= @parentChallenge.first_name %>
                        <% else %>
                            <%= FbGraph::User.new(@parentChallenge.user_id).fetch.name %>
                        <% end %>                                  
                     <span id="user_name">
                  <% else %>
                          <span id="user_name">
                              <% if isStandalone %>
                                  <%= current_user.gmauth.first_name %>
                              <% else %>
                                  <%= FbGraph::User.new(aChallenge.user_id).fetch.name %>
                              <% end %>                                  
                          </span>
                  <% end %>
<br>	
                  <% if aChallenge.start_point.instance_of?PointDateType %>
                          <%= aChallenge.start_point.value.strftime("%b %d, %Y")%> - <%= aChallenge.end_point.value.strftime("%b %d, %Y")%>
                  <% else %>
                          <%= aChallenge.start_point.value rescue 0%> - <%= aChallenge.end_point.value rescue 0%>
                  <% end %>

                  <% if aChallenge.child_challenges.size<2 %>
                   <%= aChallenge.child_challenges.size%>&nbsp;&nbsp;contestant
                   <%else%>
                  <%= aChallenge.child_challenges.size%>&nbsp;&nbsp;contestants
                  <%end%>
                  <p class="texttransormn">
                          <%=h truncate(aChallenge.description, :length => 15) %>&nbsp;&nbsp;<b><%= link_to "view" , show_soc_challenges_path(:id => aChallenge.id), :class => 'underline_view'   %>	</b>								
              </td>
              <td valign="top" width="30%" class="tdalign" >
                              <p class = "timestyle"><%= time_ago_in_words  aChallenge.created_at%></p>
              </td>
            </tr>
        </table>
    </div>
    <% end %>
<% end %>