config/routes.rb
Dojitsu::Application.routes.draw do   
  get "dashboard/index"
  get "dashboard/whatsNew"
  get "dashboard/message"
  get "dashboard/myChallenge"
  get "dashboard/dashboardIndex"
  get "dashboard/against_others"
  get "dashboard/against_myself"
  # user registration & 3rd party logins
  match 'users/auth/:provider/callback', :to=>'authentications#create'

  devise_for :users, :controllers => { :registrations => "registrations"}
  resources :authentications

  resources :challenges do
    collection do
    	post "storeWinner"
      get "show_soc"
      get "task_update"
      get "show_per"
      get "my_challenge"
      get "invitee_accepted_req"
      get "challenge_comp"
      get "task_update_c"
      get "date_updateEnd"
      get "date_updateStart"
      get "message"
      get "add_task_link"
      get "add_task_fun"
      get "update_status"
      get "socialPeople"
      get "nonLoginShowPersonal"
      get "nonLoginShowSocial"
      get "nonLoginIndex"
      get "paginationTest"
      get "update_status_af_meg"
      put "update_task_soc"
      get "scoreboard_main"
      get "filter"
      get "trophies"
      get "scoreboard"
      get "publish"
      get "title_update"
      get "task_update"
      get "desc_update"
      get "title_soc_update"
      get "desc_soc_update"
	  get "update_tasks_list"
	  put "update_tasks_list"
	  get "myscore_update_self_report"
      put :update_attribute_on_the_spot 
      get :get_attribute_on_the_spot
	  get "score_soc_update"
      get "search_people"
	  get "change_challenge_status"
	  get "update_status_again"
	  get "mForWinner"
	  get "registerToMessage"
	  get "deleteWinner"	
	  get "winnerListPopup"
	  get "whoAccepted"
	  get "whoThinking"
	  get "whoDeclined"	
	  get "myAccepted"
	  get "myDeclined"
	  get "myThinking"
    end
  end

  # static pages
  match '/aboutus', :to=>'static#aboutus'
  match '/contactus', :to=>'static#contactus'
  resources :user_connections do
    collection do
      get "sendInvitation"
      get "myDojo"
      get "people"
      get "invite_contact"
      get "delete_contact"
    end
  end

  resources :messages do
    collection do
      post "storemessage"
      get "message"
      get "newmessage"
      get "individualAllMessage"
      get "markUnread"      		
    end	
  end 


  # root page
  root :to=>'static#home'
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  field :to, :type=>String
  field :from, :type=>String
  field :subject, :type=>String
  field :snippet, :type=>String
  field :body, :type=>String
  #field :fromUserId 
  #field :toUserId
  #field :subject
  #field :body
  field :isRead ,:default => 0
  field :isDeleted, :default =>0
  #field :isFacebook # facebook OR non-facebook
  #field :messageType #sent/recive
  
  #HELPER METHODS
  def self.iAllMessage(iID,cId)
    #Message.all(conditions: { :from => iID, :isDeleted => 0, :to => cId}).desc("created_at")    
    Message.any_in(from:[iID,cId], to:[iID,cId]).desc("created_at")
  end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user! 
  
	def storemessage    
	 	@from = params[:author_id]
		@to = params[:recipients]
		@subject = params[:attachment][:name]
		@snippet = params[:snippet]
    @body = params[:body]
		@to.each do |messageTo|
			unless messageTo == @from  
				Message.create(:to => messageTo, :from => @from, :body => @body, :snippet => @snippet ,:subject => @name)
			end	
		end
		
		# ajax response
    
	end
  
  def newmessage 
    whomSend = Authentication.find_by_email(params[:to])
    UserMailer.sendMail(params[:to],params[:message]).deliver
    Message.create(:to =>whomSend.uid, :from =>current_user.fbauth.uid, :body => params[:message])
    redirect_to messages_path
  end
	
  def individualAllMessage
    @iId = params[:iId]    
    @wayToRead = Message.where(:_id => params[:id]).first
    @wayToRead.update_attributes(:isRead => 1)
    details = Authentication.find_by_uid(params[:iId])
    @toEmail = details.email    
  end
  
  def destroy
    #Message.where(:_id =>params[:id]).destroy
    aDelete = Message.where(:_id =>params[:id]).first
    aDelete.update_attributes(:isDeleted => 1)
    render 'index'
  end
  
  def markUnread    
    aUnread = Message.where(:_id =>params[:id]).first
    aUnread.update_attributes(:isRead => 0)
    render 'index'
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<section id="messagecount">
  <section id="messagecountTest">
      <%= current_user.unReadMessage.count %>
  </section>  
</section>
<%= render 'layouts/loggedinbody'%>

<%= javascript_include_tag('jquery.colorbox-min','messageJs','jquery.tools.min')%>
<%= stylesheet_link_tag('colorbox','messageCss')%>
<section class="challengeSubNav">
    <%= button_to "", "#", :class => "new_message_button_index", :method => :get%> 
    <%= link_to "MESSAGES  ",dashboard_index_url ,:class => "challenge_link" , :style=> "text-decoration: none; color:#666666; left: 15px;" %>
</section>	

<section class="challange" id="messageBox">
  <table width="100%">  
    <tr>
        <td width="64%" ><font color="#f8981d">MESSAGES</font></td>
        <td width="20%" >
          <input type="text" id="search" />
        </td>
         <script>
         function search()
         {
         var name_search=document.getElementById("search").value;
             select();    
         }
         </script>
         <td width="13%" ><div class="styled-select"> <select id="select">
           <option value="All" id="select">ALL</option>
           <option value="Unread" id="select">Unread</option>
           <option value="Archived" id="select">Archived</option>
           <option value="Sent" id="select">Send</option>
          </select> </div>
      </td>
      <td width="3%" valign="bottom">
          <%=image_tag("searchbutton.PNG",  :onclick=>"search();", :hight=>30, :width =>30 ) %>                   
      </td>
    </tr>
</table>
</section>
<table class="sortable" width="100%">  
    <thead>
      <tr><th style="CURSOR: pointer; cursor: hand;" id="content1">FROM</th><th style="CURSOR: pointer; cursor: hand;" id="content2"><span id="timespace">TIME</span></th><th width="1%"></th>
      </tr>
    </thead>
    <tbody>
        <% current_user.inbox.each do |userMessage| %>
          <% if userMessage.isRead == 1 %>
              <tr bgcolor ="#FFFFFF">
                  <td width="7%" class="bordercolortM" style="padding-left:15px;" onclick="location.href='<%= individualAllMessage_messages_path(:iId => userMessage.from, :id =>userMessage.id) %>'">
                      <%= image_tag(FbGraph::User.new(userMessage.from).fetch.picture) %>            </td>
                  <td width="81%" class="bordercolortM" style="padding-right:20px;" onclick="location.href='<%= individualAllMessage_messages_path(:iId => userMessage.from, :id =>userMessage.id) %>'">
                      <font size="3px" style="float:right; margin-top: 12px;">

                          <%#= availability_date = DateTime.parse(userMessage.created_at.to_s)%>

                          <%#= time_now = DateTime.parse(DateTime.now.to_s)%>
                          <%#= DateTime.now.in_time_zone %>

                          <%#= time_now = DateTime.parse(DateTime.now.in_time_zone.to_s) %>
                          <%#= time_until = availability_date - time_now %>
                          <%#= t = time_until.to_f %>

                          <%= time_ago_in_words userMessage.created_at %>                </font>
                      <font size="4px" style="font-weight:bold"><%= FbGraph::User.new(userMessage.from).fetch.name %></font></br>
                      <font size="3px"><%= image_tag "icon_replied.png" %> <%=h truncate(userMessage.body, :length => 55) %>..</font></br>          </td>
                  </td>
                  <td width="11%" class="bordercolortM" style="padding-left:15px;">                    
                    <% if userMessage.isRead == 0 %>
                      <%= image_tag "btn_mark_read_up.png" %>&nbsp;&nbsp;
                    <% else %>
                      <%= link_to image_tag("btn_mark_unread_up.png"), markUnread_messages_path(:id => userMessage.id), :id => "demo", :title=>"Mark as Unread"  %>&nbsp;&nbsp;
                    <% end %>                                
                    <%= link_to image_tag("icon_multiply.png"), message_path(:id => userMessage.id), :method => 'delete' %>            </td>
              </tr>
          <% else %>
              <tr bgcolor ="#F5FAF0">
                  <td width="7%" class="bordercolortM" style="padding-left:15px;" onclick="location.href='<%= individualAllMessage_messages_path(:iId => userMessage.from, :id =>userMessage.id) %>'">
                      <%= image_tag(FbGraph::User.new(userMessage.from).fetch.picture) %>            </td>
                  <td width="81%" class="bordercolortM" style="padding-right:20px;" onclick="location.href='<%= individualAllMessage_messages_path(:iId => userMessage.from, :id =>userMessage.id) %>'">
                      <font size="3px" style="float:right; margin-top: 12px;">

                          <%#= availability_date = DateTime.parse(userMessage.created_at.to_s)%>

                          <%#= time_now = DateTime.parse(DateTime.now.to_s)%>
                          <%#= DateTime.now.in_time_zone %>

                          <%#= time_now = DateTime.parse(DateTime.now.in_time_zone.to_s) %>
                          <%#= time_until = availability_date - time_now %>
                          <%#= t = time_until.to_f %>

                          <%= time_ago_in_words userMessage.created_at %>                </font>
                      <font size="4px" style="font-weight:bold"><%= FbGraph::User.new(userMessage.from).fetch.name %></font></br>
                      <font size="3px"><%= image_tag "icon_replied.png" %> <%=h truncate(userMessage.body, :length => 55) %>..</font></br>          </td>
                  </td>
                  <td width="11%" class="bordercolortM" style="padding-left:15px; ">
                    <% if userMessage.isRead == 0 %>
                      <%= image_tag "btn_mark_read_up.png" %>&nbsp;&nbsp;
                    <% else %>
                      <%= image_tag "btn_mark_unread_up.png" %>&nbsp;&nbsp;
                    <% end %>                                
                    <%= link_to image_tag("icon_multiply.png"), message_path(:id => userMessage.id), :method => 'delete' %>            </td>
              </tr>
          <% end %>        
        <% end %>
    </tbody>    
</table>

<section style="display:none;">
<section id="sendNewMessage">
    <%= form_tag newmessage_messages_path, :method => :get do  %>
    <table width="100%" bgcolor="#f4f4f4">
      <tr bgcolor="#f4f4f4">
        <td colspan="2">
          <span id="messageTextHead">New Message</span>
        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td width="17%" class="bordercolort1">
          <span id="messageText">T0</span>        
        </td>
        <td width="83%" class="bordercolort1">
          <%= text_field_tag 'to', nil, :size=>"60" %>        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td>
          <span id="messageText">MESSAGE</span>
        </td>
        <td>
          <%= text_area_tag 'message','', :class =>"textareaMessage" %>
        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td class="bordercolort1">
          &nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag("icon_attach_mo.png") %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= image_tag("icon_photo_mo.png") %>
        </td>
        <td class="bordercolort1">
          <section style="float: right;">
            <%= check_box_tag 'toMobile','', false %>
            <%= image_tag("icon_sms_mo.png") %>
          </section>
        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td colspan="2">
          <%= link_to "CANCEL",  messages_path, :style => "text-decoration: none; color:#fff; float:right" ,:class => "links_cancel_message"%>        
          <%= submit_tag "SEND", :style => "width: 80px; float:right;", :class => "linksNewMessage" %>
        </td>
      </tr>
    </table>
    <% end %>
</section>
</section>

app/views/messages/individualAllMessage.html.erb
<section id="messagecount">
  <section id="messagecountTest">
      <%= current_user.unReadMessage.count %>
  </section>  
</section>
<%= render 'layouts/loggedinbody' %>
<%= javascript_include_tag('jquery.colorbox-min','messageJs','jquery.tools.min')%>
<%= stylesheet_link_tag('colorbox','messageCss')%>
<section class="challengeSubNav">
  <%= button_to "", "#", :class => "iMessageNew", :method => :get%> 
  <%= link_to "MESSAGES >> #{FbGraph::User.new(@wayToRead.from).fetch.name.upcase}", messages_path, :class => "iMessageNewLinks", :style=> "text-decoration: none; color:#666666; left: 10px;" %>
</section>
<section>
  <table id="fdPicture" width="100%">
    <tr>
      <td width="3%"><%= image_tag(FbGraph::User.new(@wayToRead.from).fetch.picture) %></td>
      <td width="33%" id="msgOrangeColorTest"><%= FbGraph::User.new(@wayToRead.from).fetch.name.upcase   %></td>
      <td width="24%"></td>
	  <td width="19%" >
          <input type="text" id="search" />
      </td>
         <script>
         function search()
         {
             var name_search=document.getElementById("search").value;
             select();    
         }
         </script>
         <td width="12%" ><div class="styled-select"> <select id="select">
           <option value="All" id="select">ALL</option>
           <option value="Unread" id="select">Unread</option>
           <option value="Archived" id="select">Archived</option>
           <option value="Sent" id="select">Send</option>
          </select> </div>
      </td>
      <td width="3%">
          <%=image_tag("searchbutton.PNG",  :onclick=>"search();", :hight=>30, :width =>30 ) %>                   
      </td>
      <td width="3%" align="right">
          <%=image_tag("up_sort.png", :hight=>32, :width =>32 ) %>                             
      </td>
      <td width="3%" align="left">          
          <%=image_tag("dwn_sort.png", :hight=>37, :width =>37 ) %>
      </td>
    </tr>
  </table>
</section>
<section id="msgBody">
  <table id="msgBodyTable">
    <tr bordercolort>
      <td id="countMessage" class="bordercolortMDetails">
          <%= image_tag("btn_msg_expand_all_up.png") %>&nbsp;&nbsp;
          <% if Message.iAllMessage(@iId,current_user.fbauth.uid).count > 1 %>
            <%= Message.iAllMessage(@iId,current_user.fbauth.uid).count %>&nbsp;Messages
          <% else %>
            <%= Message.iAllMessage(@iId,current_user.fbauth.uid).count %>&nbsp;Message
          <% end %>          
      </td>
      <td class="bordercolortMDetails" colspan="2"><%= image_tag("icon_edit.png", :id=>"editIcone") %> </td>
    </tr>
  </table> 
  
  
  
  
 
  <section id="msgBodyTableAll">
    <% reply = 0 %>
    <% flag = 0 %>
    <% Message.iAllMessage(@iId,current_user.fbauth.uid).each do |iMessage| %>
    <section  class="bordercolort" id="<%= iMessage.from%>_<%= flag%>">
        <font id="textcolor" style="float:right">
            <%= time_ago_in_words iMessage.created_at %>                                
        </font>
        <% if iMessage.from == current_user.fbauth.uid %>
          <b style="color: #7AC142; font-size: 15px;" class="initial" id="#<%= iMessage.from%>_<%= flag%>">
            <%= FbGraph::User.new(iMessage.from).fetch.name %>
          </b>  
        <% else %>
          <b style="color: #f8981d; font-size: 15px;" class="initial" id="#<%= iMessage.from%>_<%= flag%>">
            <%= FbGraph::User.new(iMessage.from).fetch.name %>
          </b>
        <% end %>                                               
        <font id="textcolor">&nbsp;<%=h truncate(iMessage.body, :length => 80) %></font></br>    
    </section>
    
    <section  class="bordercolortR" id="<%= iMessage.from%>_<%= flag%><%= reply %>" style="display: none;">
    <% if iMessage.from == current_user.fbauth.uid %>        
        <font id="textcolor" style="float:right">
            <%= time_ago_in_words iMessage.created_at %></BR> 
            <%= image_tag "btn_mark_unread_up.png" %>&nbsp;&nbsp;
            <%= link_to image_tag("icon_multiply.png"), message_path(:id => iMessage.id), :method => 'delete' %>
        </font>
        <% if iMessage.from == current_user.fbauth.uid %>
          <b style="color: #7AC142; font-size: 15px;" class="reply" id="#<%= iMessage.from%>_<%= flag%><%= reply %>">
            <%= FbGraph::User.new(iMessage.from).fetch.name %>
          </b>  
        <% else %>
          <b style="color: #f8981d; font-size: 15px;" class="reply" id="#<%= iMessage.from%>_<%= flag%><%= reply %>">
            <%= FbGraph::User.new(iMessage.from).fetch.name %>
          </b>
        <% end %>                                               
        <font id="textcolor">&nbsp;</br><%= iMessage.body %></font></br>        
    <% else %>
        <font id="textcolor" style="float:right">
            <%= time_ago_in_words iMessage.created_at %></BR> 
            <%= link_to image_tag("btn_mark_unread_up.png"), :title=>"Mark as Unread" %>&nbsp;&nbsp;
            <%= link_to image_tag("icon_multiply.png"), message_path(:id => iMessage.id), :method => 'delete' %>                                
        </font>
        <% if iMessage.from == current_user.fbauth.uid %>
          <b style="color: #7AC142; font-size: 15px;" class="reply" id="#<%= iMessage.from%>_<%= flag%><%= reply %>">
            <%= FbGraph::User.new(iMessage.from).fetch.name %>
          </b>  
        <% else %>
          <b style="color: #f8981d; font-size: 15px;" class="reply" id="#<%= iMessage.from%>_<%= flag%><%= reply %>">
            <%= FbGraph::User.new(iMessage.from).fetch.name %>
          </b><font id="textcolorToMe">to me</font>
        <% end %>                                               
        <font id="textcolor">&nbsp;</br><%= iMessage.body %></font></br>             
          <hr width="100%">
          <%= form_tag newmessage_messages_path, :method => :get do  %>          
          <%= hidden_field_tag 'to', "#{@toEmail}" %>
          <table width="100%" bgcolor="#f4f4f4">                    
              <tr bgcolor="#ffffff">                      
                <td colspan="2">
                  <%= text_area_tag 'message','', :class =>"textareaMessageI" %>
                </td>
              </tr>
              <tr bgcolor="#ffffff">
                <td>
                  &nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag("icon_attach_mo.png") %>&nbsp;&nbsp;&nbsp;&nbsp;
                  <%= image_tag("icon_photo_mo.png") %>
                </td>
                <td>
                  <%#= link_to "CANCEL",  messages_path, :style => "text-decoration: none; color:#fff; float:right" ,:class => "links_cancel_message"%>        
                  <%= submit_tag "REPLY", :style => "width: 80px; float:right;", :class => "linksNewMessage" %>                        
                </td>
              </tr>                   
          </table>
          <% end %>
    <% end %>
    <% flag += 1 %>      
    <% reply +=1 %>    
    </section>
    <% end %>
  </section>
 

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
</section>

<section style="display:none;">
<section id="sendNewMessage">
    <%= form_tag newmessage_messages_path, :method => :get do  %>
    <table width="100%" bgcolor="#f4f4f4">
      <tr bgcolor="#f4f4f4">
        <td colspan="2">
          <span id="messageTextHead">New Message</span>
        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td width="17%" class="bordercolort1">
          <span id="messageText">T0</span>        
        </td>
        <td width="83%" class="bordercolort1">
          <%= text_field_tag 'to', nil, :size=>"60" %>        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td>
          <span id="messageText">MESSAGE</span>
        </td>
        <td>
          <%= text_area_tag 'message','', :class =>"textareaMessage" %>
        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td class="bordercolort1">
          &nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag("icon_attach_mo.png") %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= image_tag("icon_photo_mo.png") %>
        </td>
        <td class="bordercolort1">
          <section style="float: right;">
            <%= check_box_tag 'toMobile','', false %>
            <%= image_tag("icon_sms_mo.png") %>
          </section>
        </td>
      </tr>
      <tr bgcolor="#ffffff">
        <td colspan="2">
          <%= link_to "CANCEL",  messages_path, :style => "text-decoration: none; color:#fff; float:right" ,:class => "links_cancel_message"%>        
          <%= submit_tag "SEND", :style => "width: 80px; float:right;", :class => "linksNewMessage" %>
        </td>
      </tr>
    </table>
    <% end %>
</section>
</section>

app/views/messages/storemessage.erb
nothing is there