config/routes.rb
Dojitsu::Application.routes.draw do   
  get "dashboard/index"
  get "dashboard/whatsNew"
  get "dashboard/message"
  get "dashboard/myChallenge"
  get "dashboard/dashboardIndex"
  get "dashboard/against_others"
  get "dashboard/against_myself"
  # user registration & 3rd party logins
  match 'users/auth/:provider/callback', :to=>'authentications#create'

  devise_for :users, :controllers => { :registrations => "registrations"}
  resources :authentications

  resources :challenges do
    collection do
    	post "storeWinner"
      get "show_soc"
      get "task_update"
      get "show_per"
      get "my_challenge"
      get "invitee_accepted_req"
      get "challenge_comp"
      get "task_update_c"
      get "date_updateEnd"
      get "date_updateStart"
      get "message"
      get "add_task_link"
      get "add_task_fun"
      get "update_status"
      get "socialPeople"
      get "nonLoginShowPersonal"
      get "nonLoginShowSocial"
      get "nonLoginIndex"
      get "paginationTest"
      get "update_status_af_meg"
      put "update_task_soc"
      get "scoreboard_main"
      get "filter"
      get "trophies"
      get "scoreboard"
      get "publish"
      get "title_update"
      get "task_update"
      get "desc_update"
      get "title_soc_update"
      get "desc_soc_update"
	  get "update_tasks_list"
	  put "update_tasks_list"
	  get "myscore_update_self_report"
      put :update_attribute_on_the_spot 
      get :get_attribute_on_the_spot
	  get "score_soc_update"
      get "search_people"
	  get "change_challenge_status"
	  get "update_status_again"
	  get "mForWinner"
	  get "registerToMessage"
	  get "deleteWinner"	
	  get "winnerListPopup"
	  get "whoAccepted"
	  get "whoThinking"
	  get "whoDeclined"	
	  get "myAccepted"
	  get "myDeclined"
	  get "myThinking"
    end
  end

  # static pages
  match '/aboutus', :to=>'static#aboutus'
  match '/contactus', :to=>'static#contactus'
  resources :user_connections do
    collection do
      get "sendInvitation"
      get "myDojo"
      get "people"
      get "invite_contact"
      get "delete_contact"
    end
  end

  resources :messages do
    collection do
      post "storemessage"
      get "message"
      get "newmessage"
      get "individualAllMessage"
      get "markUnread"      		
    end	
  end 


  # root page
  root :to=>'static#home'
end

app/models/challenge_type.rb
class ChallengeType
  include Mongoid::Document
  field :who_win
  validates_presence_of :who_win
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_filter :authenticate_user!, :except => [:nonLoginShowPersonal, :nonLoginShowSocial, :nonLoginIndex, :registerToMessage]
  before_filter :find_challenge, :only => [:show, :edit, :update, :destroy]
  #on_spot_edit  is the gem to edit the data on spot 
  can_edit_on_the_spot

  def index
    @title = "Challenges"
    @no_of_row = Challenge.all.count
    @challenges = current_user.challenges
    @challengeCompleted = params[:id]
    @orgChallenge = Challenge.where(:_id => params[:id]).first
    cookies[:key] = "orgCompleteTask"
    #raise @orgChallenge.social_type.who_win.inspect
  end

  def show       
    @challenge = Challenge.find(params[:id])
  end

  def show_soc
    @flg = params[:flg]
    @challenge = Challenge.find(params[:id]) 
    
    #@is_complete_status = 0 
    #@challenge.tasks.each do |checkingTaskStatus|
    #  unless checkingTaskStatus.is_complete == 1
    #    @is_complete_status = 1
    #    next
    #  end
    #end
    #if @is_complete_status == 0
    #  Challenge.where(:_id => params[:id]).update(:is_complete => 1)
    #end
    @org = User.find(:all,:conditions => ["id=?",@challenge.user_id]).first
  end
  
  def scoreboard_main
    @challenge = Challenge.find(params[:id])
    @this_tasks = @challenge.tasks
    @challenge.child_challenges.each do |childid|
      @cid = childid.user_id 
    end
    @challenge.child_challenges.each do |chalid|
      @chaid = chalid.challenge_id 
    end
  end

  def show_per
    @challenge = Challenge.find(params[:id])
    #GETING ALL USER CONNECTION
    aConnection = []
    @allConnections = UserConnection.select(:target_id).where(:user_id=>current_user.id)
    @allConnections.each do |aTargetId|
      aConnection.push(aTargetId.target_id)
    end     
    #ALL CONNECTION AS PARTICIPANT
    @onlyMyFrd = Challenge.all(conditions: {:user_id.in => aConnection, :title => @challenge.title })
    #ALL FRD IN CHALLENGE
    @onlyMyFrdInChallenge = [] 
    @myAccepted = [] 
    @myThinking = []
    @myDeclined = []
    @onlyMyFrd.each do |aStatus|
    	@onlyMyFrdInChallenge.push(aStatus.user_id)
      if aStatus.social_type.status == 1
        @myAccepted.push(aStatus.user_id)
      elsif aStatus.social_type.status == -1
        @myDeclined.push(aStatus.user_id)
      else
        @myThinking.push(aStatus.user_id)
      end
    end
    
    #raise @myAccepted.inspect
    #raise @myDeclined.inspect
    #raise @myThinking.inspect
    
    #MARK CHALLENGE AS COMPLETE
    #@is_complete_status = 0 
    #@challenge.tasks.each do |checkingTaskStatus|
    #  unless checkingTaskStatus.is_complete == 1
    #    @is_complete_status = 1
    #    next
    #  end
    #end
    #if @is_complete_status == 0
    #  Challenge.where(:_id => params[:id]).update(:is_complete => 1)
    #end
    if (@challenge.social_type.instance_of? ChallengeSocialType rescue false)
      render "show_soc" and return 
    else 
      render "show_per"
    end
  end
  
  

  def new
    @challenge = Challenge.new
    1.times {@challenge.tasks.build} 
  end

  def create
    
    @ch = Challenge.new(params[:challenge])
    @ch_st_date = params[:start_point_type]
    @st_p_val = params[:start_point_value]
    @st_p_leb = params[:start_point_label]

    @ch_ed_date = params[:end_point_type]
    @ed_p_val = params[:end_point_value]
    @ed_p_leb = params[:end_point_label]

    @so_who_win = params[:soc_who_win]
    @so_how_many_winner = params[:soc_how_many_winner]
    @pr_who_win = params[:per_who_win]

    unless @so_who_win.blank?
      @challenge = Challenge.new(:user_id => (current_user.fbauth.uid rescue current_user.id), :title => @ch.title, :description => @ch.description, :canCompleteBeforeTasks => @ch.canCompleteBeforeTasks, \
          :social_type => ChallengeSocialType.new(:status => 1,:who_win => @so_who_win, :how_many_winners => @so_how_many_winner, :trophy => Trophy.new(:rank=>0))) do |new_challenge|
        if @ch_st_date == "startPointDate" and  @ch_ed_date == "endPointDate"
          new_challenge.start_point =  PointDateType.new(:value => Date.strptime(@st_p_val, '%m/%d/%Y'))
          new_challenge.end_point = PointDateType.new(:value => Date.strptime(@ed_p_val, '%m/%d/%Y')) 
        else
          new_challenge.start_point =  PointNumberType.new(:value => @st_p_val, :label=> @st_p_leb)
          new_challenge.end_point = PointNumberType.new(:value => @ed_p_val, :label=>@ed_p_leb) 
        end
      end
    else
      @challenge = Challenge.new(:user_id => (current_user.fbauth.uid rescue current_user.id), :title => @ch.title, :description => @ch.description, :canCompleteBeforeTasks => @ch.canCompleteBeforeTasks, \
          :personal_type => ChallengePersonalType.new(:who_win => @pr_who_win)) do |new_challenge|
        if @ch_st_date == "startPointDate" and  @ch_ed_date == "endPointDate" 
          new_challenge.start_point =  PointDateType.new(:value => Date.strptime(@st_p_val, '%m/%d/%Y'))
          new_challenge.end_point = PointDateType.new(:value => Date.strptime(@ed_p_val, '%m/%d/%Y')) 
        else
          new_challenge.start_point =  PointNumberType.new(:value => @st_p_val, :label=> @st_p_leb)
          new_challenge.end_point = PointNumberType.new(:value => @ed_p_val, :label=>@ed_p_leb) 
        end
      end            
    end

    @ch.task_attributes.each do |task_attr|
      @challenge.tasks.build(task_attr)
    end

    @challenge.save!
	
    unless @so_who_win.blank?
      # referenced documents can only be saved when parent exists
      if !params[:invitees].nil?
        params[:invitees].split(",").each do |aFBId|
          current_user.user_connections.find_or_create_by_target_id(:target_id => aFBId )
        end
      end
    end
		

    unless @so_who_win.blank?
      # referenced documents can only be saved when parent exists
      if !params[:invitees].nil?
        params[:invitees].split(",").each do |invitee|
          if @ch_st_date == "startPointDate" and  @ch_ed_date == "endPointDate"
            @challenge.child_challenges.create!(:user_id => invitee, :title => @ch.title, :description => @ch.description, :canCompleteBeforeTasks => @ch.canCompleteBeforeTasks, \
                :start_point => PointDateType.new(:value => Date.strptime(@st_p_val, '%m/%d/%Y')), \
                :end_point => PointDateType.new(:value => Date.strptime(@ed_p_val, '%m/%d/%Y')), \
                :social_type => ChallengeSocialType.new(:who_win => @so_who_win, :how_many_winners => @so_how_many_winner, :trophy => Trophy.new(:rank=>0)), \
                :tasks => @ch.task_attributes)
          else 
            @challenge.child_challenges.create!(:user_id => invitee, :title => @ch.title, :description => @ch.description, :canCompleteBeforeTasks => @ch.canCompleteBeforeTasks, \
                :start_point => PointNumberType.new(:value => @st_p_val, :label=> @st_p_leb), \
                :end_point => PointNumberType.new(:value => @ed_p_val, :label=>@ed_p_leb), \
                :social_type => ChallengeSocialType.new(:who_win => @so_who_win, :how_many_winners => @so_how_many_winner, :trophy => Trophy.new(:rank=>0)), \
                :tasks => @ch.task_attributes)
          end
        end      
      end  
    end   
    redirect_to show_per_challenges_path(:id => @challenge, :isNewChallenge => "isNew"), :notice => "Challenge created!" 

  

  end
  def publish
    render :layout => false 
  end
  def edit
    @challenge = Challenge.find(params[:id])
  end

  def update_task_soc
    @challenge = Challenge.find(params[:id])
    Challenge.where(:_id => params[:id]).update(:canCompleteBeforeTasks => params[:challenge][:canCompleteBeforeTasks])
    @challenge.tasks.destroy
    @challenge.child_challenges.each do |eachChildChallenge|
      eachChildChallenge.update_attributes(:canCompleteBeforeTasks => params[:challenge][:canCompleteBeforeTasks])
      eachChildChallenge.tasks.destroy
      eachChildChallenge.update_attributes(params[:challenge])
    end
    @challenge.update_attributes(params[:challenge])
    redirect_to show_soc_challenges_path(:id => @challenge)
  end

  def update
    @challenge = Challenge.find(params[:id])
	
    if @challenge.update_attributes(params[:challenge])
      #raise "aaa"
      redirect_to :action => 'index', :id => @challenge
    else
      render :action => edit
    end
  end
	
  def destroy
    @challenge.destroy
    redirect_to :action => 'index'
  end  

  def invitee_accepted_req
    
  end

  def message
    render :partial => 'challenges/message'
  end  

  def task_update
    @id = params[:id]
    @name = params[:name]
    @score = params[:score]
    @score_by = params[:score_by]
    render :layout => false
  end

  def task_update_c
    @ch_ts_update = Challenge.find(params[:id])
    unless params[:tatal_s]
      if params[:task_done] == "yes"
        @ch_ts_update.tasks.where(:name => params[:name]).update(:is_complete => 1)
        redirect_to show_per_challenges_path(:id => params[:id], :isNewChallenge => "isNew")
        return
      end
      redirect_to show_per_challenges_path(:id => params[:id])
      return
    else
      @ch_ts_update.tasks.where(:name => params[:name]).update(:is_complete => 1, :score => params[:tatal_s])
      redirect_to show_per_challenges_path(:id => params[:id], :isNewChallenge => "isNew")
      return
    end 
  end

  
  def search_people
		render :layout => false
  end
  
  
  def challenge_comp
    Challenge.where(:_id => params[:id]).update(:is_complete => 1)
    redirect_to show_per_challenges_path(:isNewChallenge => "isNew", :id => params[:id])
  end

  def my_challenge
    @my_total_challenge = Challenge.all.count
    @my_all_ch = Challenge.all
    @my_all_ch.each do |sd|
      @org = User.find(:all,:conditions =>["id = ?",sd.user_id]).first
    end
  end

  def add_task_link
    @ch_id = params[:id]
    render :layout => false
  end

  def add_task_fun
    @chall_ref = Challenge.find(params[:challenge_id]) 

app/helpers/challenges_helper.rb
module ChallengesHelper

	def markAsComplete
		allTaskComplete = 0
    if isStandalone
      if @challenge.user_id == current_user.gmauth.id
        if @challenge.canCompleteBeforeTasks? 
          @challenge.tasks.each do |aTask| 
            if aTask.is_complete == 0 
              allTaskComplete = 1 			
            end 
          end
          if allTaskComplete == 1 
            link_to "I'm Done with this challenge >> Submit my score",  "#", :style => "text-decoration: none; color:#fff; float:right; position:relative; top:-5px; right: -10px;" ,:class => "links_score_p" 
          else 
            link_to "I'm Done with this challenge >> Submit my score",  challenge_comp_challenges_path(:id=>@challenge), :style => " position:relative; top:-5px; text-decoration: none; color:#fff; float:right; right: -10px;" ,:class => "links_score_p"
          end
        else
          link_to "I'm Done with this challenge >> Submit my score",  challenge_comp_challenges_path(:id=>@challenge), :style => " position:relative; top:-5px; text-decoration: none; color:#fff; float:right; right: -10px;" ,:class => "links_score_p"
        end
		else
			link_to "I'm Done with this challenge >> Submit my score",  "#", :style => " position:relative; top:-5px; text-decoration: none; color:#fff; float:right right: -10px;" ,:class => "links_score_p"
		end 
    else
      if @challenge.user_id == current_user.fbauth.uid
        if @challenge.canCompleteBeforeTasks? 
          @challenge.tasks.each do |aTask| 
            if aTask.is_complete == 0 
              allTaskComplete = 1 			
            end 
          end
          if allTaskComplete == 1 
            link_to "I'm Done with this challenge >> Submit my score",  "#", :style => "text-decoration: none; color:#fff; float:right; position:relative; top:-5px; right: -10px;" ,:class => "links_score_p"
          else 
            link_to "I'm Done with this challenge >> Submit my score",  challenge_comp_challenges_path(:id=>@challenge), :style => " position:relative; top:-5px; text-decoration: none; color:#fff; float:right; right: -10px;" ,:class => "links_score_p"
          end
        else
          link_to "I'm Done with this challenge >> Submit my score",  challenge_comp_challenges_path(:id=>@challenge), :style => " position:relative; top:-5px; text-decoration: none; color:#fff; float:right; right: -10px;" ,:class => "links_score_p"
        end
		else
			link_to "I'm Done with this challenge >> Submit my score",  "#", :style => " position:relative; top:-5px; text-decoration: none; color:#fff; float:right right: -10px;" ,:class => "links_score_p"
		end
    end	
	end	
	
end

app/views/challenges/index.slim
= stylesheet_link_tag "colorbox"
= javascript_include_tag "jquery.colorbox-min","fbWallPost"
= render partial="layouts/loggedinbody"


-if params[:isNewChallenge] == "isNew"
    javascript:
      $.dojitsuWallPost.renderFbWallPost();
    

.span-24.challengeSubNav
	.span-8
		.span-4   &nbsp;
		.span-2.right
   			= button_to "", new_challenge_url, :class => "new_challenge_button_new", :method => :get
    
	= link_to "MY CHALLENGES  ",challenges_url ,:class => "challenge_link" , :style=> "text-decoration: none; color:#666666;"

	
	
- unless @challenges.empty?
	table
	  - for challenge in @challenges do
	      tr
	        td = link_to challenge.title, {:action => 'show_per', :id => challenge.id },:style=> "text-decoration: none; font-weight:bold; color:#666666;"
- else
    p No Challenges found   

app/views/challenges/invite.html.erb
<%= stylesheet_link_tag('jquery.facebook.multifriend.select.css','challenges.css','jquery-ui')%>

<%= form_for :challenge, :url => {:controller=> "challenges",:action => "create"},:html=>{:multipart => true, :name => "challenge_form", :onclick=> "return validate_form_fields(this);"} do |f| -%>
			<p>            
			 <%= image_tag("invitee.PNG", :id => "inviteBtn",   :class=>"invitees" )%>
			  
			 <%= text_field_tag :invitees, nil , :id => "invitees_id", :class=> "hidden" %>
			</p>                             
<% end %>

app/views/challenges/new.html.erb
<%= stylesheet_link_tag('simple-tabs_new.css','jquery-ui.css','jquery.cluetip.css','challenges.css')%>
<%= javascript_include_tag('simple-tabs','jquery.table.addrow.js','jquery.cluetip.js','challenge_new')%>

<%= render 'layouts/loggedinbody'%>

<div class="challengeSubNav">

   	<%=link_to( image_tag("newbutton.PNG"), new_challenge_url, :class => "new_challenge_button_new1", :method => :get )%>
    
	<%= link_to "MY CHALLENGES >> ",challenges_url , :class => "challenge_link1" %>
	
	<%= link_to "CREATE NEW ",new_challenge_url , :class => "challenge_link1" %> 

</div>

<div class="pageContainer">
	<span class="pageTitle">CREATE NEW</span>

	<%= form_for :challenge, :url => {:controller=> "challenges",:action => "create"},:html=>{:multipart => true, :name => "challenge_form", :onSubmit => "return validate_form_fields(this);"} do |f| -%>
	<table width="100%" border="0" class ="challengecre">
		<tr >
			<td colspan="4">
			<%= f.text_field :title, :class => "textfield_effect_nw_tk_title", :placeholder=>"Enter challenge title here" , :required => "required", :maxlength => "30" , :onkeyup => "sync()" %><div id="title"></div>
			</td>	
		</tr>
	
		<tr >
			<td colspan="4">
				<hr id="all_hr">
			</td>
		</tr>
		<tr>
			<td  class="color999"><%= f.label :description, "DESCRIPTION" %></td>
			<td  colspan="3"><%= f.text_area :description, :class => "textarea_nw_tk", :id => "on_focus_textarea", :placeholder=>"Enter challenge description here" %></td>
		<script>
$(".textarea_nw_tk").click(function () {
  alert("checking");
</script>

		</tr>
		<tr>
				<td colspan="4">
					<hr id="all_hr">
				</td>
		</tr>
		<tr>
				<td width="13%"><b class="color999">STARTING POINT</b></td>
				<td width="50px;"> 
				    <div class="styled-select">
					<%= select_tag "start_point_type", "<option value=''>Choose</option><option value='startPointDate'>Date</option><option value='startPointNumber'>Number</option>".html_safe , :required => "required" %>
					</div>
				</td>  
				<td colspan="2">					
					<div class="startPointDate">
					</div>
					<div class="startPointNumber">
					</div>				
				</td>  
		</tr>
		<tr>
				<td colspan="4">
					<hr id="all_hr">
				</td>
		</tr>
		<tr>  
				<td><b class="color999">END POINT</b></td>
				<td>  
					<div class="styled-select">
					<%= select_tag "end_point_type", "<option  value=''>Choose</option><option value='endPointDate'>Date</option><option value='endPointNumber'>Number</option>".html_safe, :required => "required" %>
					</div>
				</td>  
				<td colspan="2" class="endpointdatenumber">					
					<div class="endPointDate">
					</div>
					<div class="endPointNumber">
					</div>				
				</td>
		</tr>
		<tr>
				<td colspan="4">
					<hr id="all_hr">
				</td>
		</tr>
		<tr>
				<td valign="top">
					<b class="color999"> CREATE TASKS</b> 
					<span class="moreInfoTip color999" style="background:#ffffff;" title="The score for each task will be added up to determin the winner(s)." rel="#moreCreateTaskId" >
						<%= image_tag("btn_questionmark_up.png")%>
					</span>
				
				</td>
				<td colspan="3">
					<table border="1">
						<tr>
							<th colspan="2" class="color999" valign="bottom">Score this task by</th>
							<th colspan="2" class="color999" valign="bottom">Point(s)</th>
							<th colspan="2" class="color999" valign="bottom">Task(name)
							</th>
						</tr>

						<% @challenge.tasks.each_with_index do |task, index| %>      
						<%= f.fields_for "task_attributes[]", task do |task_fields| %>						
						<tr>
							<td width="25%" class="taskSelection">
							<div class="styled-select">
								<%= task_fields.select :score_by, options_for_select([
								["Choose", ""],
								["Check box:1 for checking off the task", "Check box:1 for checking off the task"],	 
								["Self-reported number","Self-report number"]														
								]), :class => "styleselect", :required => "required"%>	
							</td>
							</div>
							<td align="center" class="taskIcon"><%= image_tag("icon_multiply.png")%></td>
							<td align="center">     
								<%= task_fields.text_field :score, :class => "textfield_effect_nw_tk_add", :size=>"10px",:required => "required", :placeholder=>"Enter task point(s)" %>
							</td>
							<td align="center" class="taskIcon"><%= image_tag("icon_slash.png")%></td>
							<td align="center">     
								<%= task_fields.text_field :name, :class => "textfield_effect_nw_tk", :required => "required",  :placeholder=>"Enter task name here"%>
							</td>				
							<td>
								<%= image_tag("btn_delete_up.png" ,:class => "delRow") %>			
							</td>
						</tr>
						<tr>
							<td colspan="5"><hr id="all_hr1"></td>									
							<td align="right">
							<%= image_tag("btn_add_up.png", :class => "addRow")%>
								
							</td>
						</tr>
							
						<% end %> 
						<% end %>
						<tr>
							<td colspan="6">
								<b class="color999"><%= image_tag("icon_arrow_left.png")%>&nbsp;&nbsp;Do all tasks need to be complete before the challenge is marked complete?</b><br>
								<span class="spacing2"><%= f.radio_button :canCompleteBeforeTasks, "1", :class => "chall_type" ,:checked =>"checked"%>
								<span class="color999"><%= f.label "Yes" %></span></span><span class="spacing"></span>
								<%= f.radio_button :canCompleteBeforeTasks, "0", :class => "chall_type"%>
								<span class="color999"><%= f.label "No" %></span>							   
							</td>
						</tr>    
					</tr> 
					</table>
				</td>
				</tr>
				<tr>
					<td colspan="4">
						<hr id="all_hr">
					</td>
				</tr>
				<tr>
					<td valign="top"><b class="color999">PRIVACY</b></td>
					<td colspan="3">
					<ul style="background:#f4f4f4;" class="tabs">
    					<li><a href="#tab1" id="soc">Social</a></li>
    					<li><a href="#tab2" id="per">Personal</a></li>
					</ul>

					<div class="tab_container">
    					<div id="tab1" class="tab_content">
    						
		<table cellspacing="10px" width="100%" border="0">
		<tr>
			<td width="25%"><b class="color999">Who wins?</b></td>
			<td>
				<div class="styled-select1">
				<%= select_tag :soc_who_win, options_for_select([
					["Choose", ""],							
					["Highest number of points","Highest number of points"],
					["Lowest number of points","Lowest number of points"],	 
					["1st person to reach End Point","1st person to reach End Point"],	
					["Participant completes all tasks","Participant completes all tasks"]			 														
					]), :id => "soc_wn", :class => "selectagwidth"
					%>		
				</div>	
				<div id="select_challenge_div"></div>
			</td>
			</tr>
			<tr>
				<td><b class="color999">How many winners?</b></td>
				<td>
					<div class="styled-select1">
					<%= select_tag :soc_how_many_winner, options_for_select([
						["Choose", ""],
						["1", "1"],							
						["3","3"],
						["5","5"],	 
						["All participants win","all"] 														
						]), :id => "soc_hm", :class => "selectagwidth"
						%>
					</div>		
						<div id="soc_how_many_winner_div"></div>	
					</td>
				</tr>

				<tr id="add_participant">
					<td ><b class="color999">Participants</b></td>
					<td id="participant">
						<%= render :partial => 'invitations', :locals => {:form => f} %>
					</td>
				</tr>
                                <tr id="add_participant">
                                  <td></td>
                                  <td  ><input type="checkbox" ><span id="addparticipant">Add myself as one of the participants</span></td>
                                </tr>
	</table>
    					</div>
    					<div id="tab2" class="tab_content">
       						<table width="100%" border="0">
  								<tr>
    								<td  width="20%"><b class="color999">Who wins?</b></td>
									<td>
										<div class="styled-select1">
										<%= select_tag :per_who_win, options_for_select([
    										["Choose", ""],							
											["Add all points together","Add all points together"],
											["Reach all milestones","Reach all milestones"]
 											]), :id => "per_wn", :class => "selectagwidth" 
 										%>
										</div>
									</td>
  								</tr>
							</table>  
    					</div>
					</div>	
		
	
					</td>
				</tr>
				<tr>
					<td colspan="4">
						<hr id="all_hr">
					</td>
				</tr>
        </table> 
		
                                 <input type="checkbox" onclick="showMe('div1', this)"><span id="savechallenge">Save this challenge as  template in my profile</span>
								 <div class="row" id="div1" style="display:none"><span id="templatename">TEMPLATE NAME</span><input id="templatenameinput" type="text" readonly></div>
                                
								<table>
                                <tr>
                                  <td colspan="4">
						<hr id="all_hr">
					</td>
                                </tr>
				<tr>
					<td colspan="4">
						<%= link_to "CANCEL", challenges_path, :class => "links_cancel1"%>
						<%= f.submit "DONE" ,  :class => "linksnew" %>
					
					</td>
				</tr> 
			</table> 
		</td>	
	</tr>						
	<% end %>	
</div>
<div id="moreCreateTaskId">

	<table id="challengenewpopuptable" height="160">						
		<tr>
			<td><p style="color:#F8991F; font-size:13px; margin-top:5px;"><b>Check box:</b></p></td>
			<td ><input id="popupboxfirst" type="text" value="1(on checking off the task)" size="18" readonly></td>
			<td ><%= image_tag("icon_multiply.png", :height => '11', :width => '9')%></td>
			<td ><input id="popupboxsecond" type="text" value="point(s) per task" size="14" /></td>
			<td ><%= image_tag("icon_equal.png", :height => '8', :width => '7')%></td>
			<td ><input id="popupboxthird" type="text" value="Score" size="5" /></td>
		</tr>
		<tr>
		    <td colspan="6"><hr></td>
		</tr>
		<tr>
			<td ><p style="color:#F8991F; font-size:13px; margin-top:5px;"><b>Data entry:</b></p></td>
			<td ><input id="popupboxfirst" type="text" value="Number of days to finish the task" size="18" readonly></td>
			<td ><%= image_tag("icon_multiply.png", :height => '11', :width => '9')%></td>
			<td ><input id="popupboxsecond" type="text" value="point(s) per task" size="14" /></td>
			<td ><%= image_tag("icon_equal.png", :height => '8', :width => '7')%></td>
			<td ><input id="popupboxthird" type="text" value="Score" size="5" /></td>
		</tr>
		<tr>
		    <td colspan="6"><hr></td>
		</tr>
		<tr>
			<td ><p style="color:#F8991F; font-size:13px; margin-top:5px;"><b>Self-reported Number:</b></p></td>
			<td ><input id="popupboxfirst" type="text" value="Number" size="18" readonly></td>
			<td ><%= image_tag("icon_multiply.png", :height => '11', :width => '9')%></td>
			<td ><input id="popupboxsecond" type="text" value="point(s) per task" size="14" /></td>
			<td ><%= image_tag("icon_equal.png", :height => '8', :width => '7')%></td>
			<td ><input id="popupboxthird" type="text" value="Score" size="5" /></td>
		</tr>
		<div id="checkboxtext1"> e.g., checking off "do laundry(3 points)" task scores 3 points </div>
		<div id="checkboxtext2"> e.g., taking 3 days to finish "lose 1 pond" task scores 3 points </div>
		<div id="checkboxtext3"> e.g., reporting 10 miles for"run treadmil(2 points)" task scores 20 points </div>
		
	</table>			
</div>